site_name: Honda Stepwgn
site_description: База знаний Honda Stepwgn 5го поколения (RP1, RP2, RP3, RP4, RP5). Информация о комплектациях, обслуживании, расходниках, инструкции и руководства пользователя
site_url: https://stepwgn.github.io/

nav:
  - Главная: index.md
  - 5 поколение (RP1-5):
    - Комплектации: 5g/configurations.md
    - Библиотека: 5g/library.md
    - Обслуживание:
      - Запчасти и расходники: 5g/service/parts.md
      - Двигатель: 5g/service/engine.md
      - Вариатор: 5g/service/variator.md
      - Тормозная система: 5g/service/brake-system.md
      - Колеса и диски: 5g/service/wheels.md
    - Диагностика и настройка:
      - Бортовой компьютер: 5g/setup/board-computer.md
      - Климат-контроль: 5g/setup/climate-control.md
    - Руководства:
      - Руководство по ремонту кузова:
        - О руководстве: 5g/manuals/body/about.md
        - Как читать эту книгу: 5g/manuals/body/000000000000001.md
        - Условные обозначения: 5g/manuals/body/000000000000002.md
        - Точка измерения размеров/место нанесения герметика: 5g/manuals/body/000000000000003.md
        - Единицы измерения: 5g/manuals/body/000000000000004.md
        - Идентификация единицы: 5g/manuals/body/000000000000005.md
        - Диапазон сварки деталей из высокопрочной стали (1500 МПа): 5g/manuals/body/000000000000006.md
        - Меры предосторожности при снятии аккумулятора 12 В: 5g/manuals/body/000000000000007.md
        - Точка подъема домкрата: 5g/manuals/body/000000000000008.md
        - Точки подъема (точки опоры): 5g/manuals/body/000000000000009.md
        - Внешний вид/регулировка колес: 5g/manuals/body/000000000000010.md
        - Конфигурация сборочной детали: 5g/manuals/body/000000000000011.md
        - Конфигурация частей тела: 5g/manuals/body/000000000000012.md
        - Обзор ремонтных работ на участках с использованием высокопрочных стальных пластин: 5g/manuals/body/000000000000013.md
        - Обзор замены деталей: 5g/manuals/body/000000000000014.md
        - Условия сварки MAG для деталей из высокопрочной листовой стали: 5g/manuals/body/000000000000015.md
        - Меры предосторожности при эксплуатации транспортных средств, оборудованных системами подушек безопасности SRS: 5g/manuals/body/000000000000016.md
        - Условия пайки MIG для деталей из высокопрочной листовой стали (1500 МПа): 5g/manuals/body/000000000000017.md
        - Условия точечной сварки деталей из высокопрочной листовой стали (1500 МПа): 5g/manuals/body/000000000000018.md
        - Материал внешних деталей из смолы: 5g/manuals/body/000000000000019.md
        - Материалы и характеристики деталей из смолы: 5g/manuals/body/000000000000020.md
        - Цвет краски: 5g/manuals/body/000000000000021.md
        - Меры предосторожности при покраске: 5g/manuals/body/000000000000022.md
        - Снятие передней перегородки: 5g/manuals/body/000000000000023.md
        - Установка передней перегородки: 5g/manuals/body/000000000000024.md
        - Снятие передней колесной арки/корпуса амортизатора: 5g/manuals/body/000000000000025.md
        - Установка передней колесной арки/корпуса амортизатора: 5g/manuals/body/000000000000026.md
        - Снятие передних боковых рам/аутригеров: 5g/manuals/body/000000000000027.md
        - Установка передних боковых рам/аутригеров: 5g/manuals/body/000000000000028.md
        - Снятие внешней панели передней стойки: 5g/manuals/body/000000000000029.md
        - Установка наружной панели передней стойки: 5g/manuals/body/000000000000030.md
        - Снятие внешней панели бокового порога: 5g/manuals/body/000000000000031.md
        - Монтаж внешней панели бокового порога: 5g/manuals/body/000000000000032.md
        - Снятие внешней панели центральной стойки: 5g/manuals/body/000000000000033.md
        - Установка внешней панели центральной стойки: 5g/manuals/body/000000000000034.md
        - Снятие боковых удлинителей порогов: 5g/manuals/body/000000000000035.md
        - Установка боковых удлинителей порогов: 5g/manuals/body/000000000000036.md
        - Снятие панели крыши: 5g/manuals/body/000000000000037.md
        - Монтаж кровельных панелей: 5g/manuals/body/000000000000038.md
        - Снятие задней боковой внешней панели: 5g/manuals/body/000000000000039.md
        - Установка задней боковой наружной панели: 5g/manuals/body/000000000000040.md
        - Снятие третьего поддона сиденья/задней рамы: 5g/manuals/body/000000000000041.md
        - Установка третьего сиденья/задней рамы: 5g/manuals/body/000000000000042.md
        - Положение и размер изолятора: 5g/manuals/body/000000000000043.md
        - Снятие задней поперечины: 5g/manuals/body/000000000000044.md
        - Установка задней поперечины: 5g/manuals/body/000000000000045.md
        - Размеры днища кузова — передний пол и задний пол: 5g/manuals/body/000000000000046.md
        - Фактические размеры верхней части кузова — положение переднего крыла и перегородки (в неразобранном виде): 5g/manuals/body/000000000000047.md
        - Измерения верхней части тела - положение передней переборки: 5g/manuals/body/000000000000048.md
        - Таблица модификаций — вид сбоку полноприводного автомобиля: 5g/manuals/body/000000000000049.md
        - Таблица коррекции — план этажа полноприводного автомобиля: 5g/manuals/body/000000000000050.md
        - Таблица модификаций — вид сбоку автомобиля 2WD: 5g/manuals/body/000000000000051.md
        - Таблица поправок — план этажа автомобиля с приводом на два колеса: 5g/manuals/body/000000000000052.md
        - Размеры днища - Положение удлинения бокового порога: 5g/manuals/body/000000000000053.md
        - Размеры днища кузова — передний пол и задний пол: 5g/manuals/body/000000000000054.md
        - Размеры днища кузова - моторный отсек и передний пол: 5g/manuals/body/000000000000055.md
        - Фактические размеры днища кузова - положение подрамника (в неразобранном виде): 5g/manuals/body/000000000000056.md
        - Фактические размеры верхней части корпуса - Установка сборочных деталей: 5g/manuals/body/000000000000057.md
        - Размеры верхней части кузова - открытие задней двери: 5g/manuals/body/000000000000058.md
        - Фактические размеры верхней части корпуса - моторный отсек: 5g/manuals/body/000000000000059.md
        - Размеры верхней части кузова — место крепления двигателя/трансмиссии: 5g/manuals/body/000000000000060.md
        - Фактические размеры верхней части корпуса - Положение нижнего элемента рулевой рубки: 5g/manuals/body/000000000000061.md
        - Размеры верхней части корпуса - Положение дверных петель: 5g/manuals/body/000000000000062.md
        - Фактические размеры верхней части корпуса - Положение женского стопора/фиксатора раздвижной двери: 5g/manuals/body/000000000000063.md
        - Фактические размеры верхней части тела - пол: 5g/manuals/body/000000000000064.md
        - Фактические размеры верхней части корпуса - положение направляющей панели раздвижной двери: 5g/manuals/body/000000000000065.md
        - Фактические размеры верхней части корпуса - внутреннее положение панели: 5g/manuals/body/000000000000066.md
        - Фактические размеры верхней части кузова — положение желоба задней стойки/задней панели: 5g/manuals/body/000000000000067.md
        - Размеры верхней части тела - переднее окно, дверной проем: 5g/manuals/body/000000000000068.md
        - Точки уплотнения - задняя часть передней боковой рамы, аутригеры: 5g/manuals/body/000000000000069.md
        - Защита грунтовки/внутренней поверхности от ржавчины - Зоны защиты внутренней поверхности от ржавчины: 5g/manuals/body/000000000000070.md
        - Грунтовка/Внутренняя поверхность антикоррозийная - Область нанесения грунтовки: 5g/manuals/body/000000000000071.md
        - Антикоррозийное покрытие для внутренних поверхностей. Меры предосторожности при работе.: 5g/manuals/body/000000000000072.md
        - Точки уплотнения - арка заднего колеса: 5g/manuals/body/000000000000073.md
        - Места уплотнения - желоб задней стойки, задняя панель: 5g/manuals/body/000000000000074.md
        - Точки уплотнения - передний пол, задний пол: 5g/manuals/body/000000000000075.md
        - Точки уплотнения - верхняя панель приборов, нижняя панель приборов: 5g/manuals/body/000000000000076.md
        - Точки уплотнения - моторный отсек/передняя колесная арка, корпус амортизатора: 5g/manuals/body/000000000000077.md
        - Точки уплотнения - Меры предосторожности при работе: 5g/manuals/body/000000000000078.md
        - Точки уплотнения - панель крыши, внешняя боковая панель: 5g/manuals/body/000000000000079.md

  - Мультимедиа: multimedia.md
  - Полезные контакты: contacts.md

theme:
  name: material
  custom_dir: overrides
  language: ru
  logo: assets/logo.png
  favicon: /icons/favicon.ico
  features:
    - content.code.copy
    - content.footnote.tooltips
    - content.tooltips
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.follow

extra:
  analytics:
    provider: google
    property: G-KLZQKM471D
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Moscow
      exclude:
        - index.md
  - include-markdown
  - search
  - social

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
