site_name: Honda Stepwgn

nav:
  - Главная: index.md
  - 5 поколение (RP1-5):
      - Комплектации: 5g/configurations.md
      - Обслуживание:
          - Запчасти и расходники: 5g/service/parts.md
          - Двигатель: 5g/service/engine.md
          - Вариатор: 5g/service/variator.md
          - Тормозная система: 5g/service/brake-system.md
          - Колеса и диски: 5g/service/wheels.md
      - Руководства: 5g/downloads.md
  - Мультимедиа: multimedia.md
  - Полезные ссылки: links.md

theme:
  name: material
  language: ru
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    - content.footnote.tooltips
    - content.tooltips
    - navigation.footer

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Moscow
      exclude:
        - index.md
  - include-markdown
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
