with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:546.07px;\" coordsize=\"950.00,546.07\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:546.07px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/105_2.0_jpn_15145737_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:546.07px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15.959436px;top:9.485066px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Единица: мм/φ: диаметр отверстия</font></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.211204px;top:518.880439px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">uПравильно</font></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.765557px;top:518.880439px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">u Левый</font></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518.876409px;top:505.879248px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">r</font></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649.609520px;top:386.701747px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;background-color:#ffffff;left:649.609520px;top:427.149867px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;background-color:#ffffff;left:248.020556px;top:394.646908px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.020556px;top:355.643375px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142.567338px;top:359.254797px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b1<br>b3</font></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177.959174px;top:487.099753px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c1</font></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168.569499px;top:351.309637px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b2</font></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221.296114px;top:487.099753px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c2</font></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200.349919px;top:487.099753px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c3</font></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199.627638px;top:342.642183px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d1</font></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227.796643px;top:340.475325px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d2</font></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283.017760px;top:353.241418px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">e</font></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276.376909px;top:402.274708px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a2</font></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274.744999px;top:520.325027px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">f1、<br>f2</font></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293.048745px;top:401.247780px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">g</font></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371.147244px;top:401.247780px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">k</font></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157.012980px;top:487.099753px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a1</font></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728.338308px;top:391.757779px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o3</font></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323.858250px;top:401.964342px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h1</font></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386.910205px;top:401.964342px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h3</font></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361.116258px;top:401.964342px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h2</font></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:423.131539px;top:520.255447px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h4</font></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702.170175px;top:499.410189px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">v </font></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766.619266px;top:401.869796px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">m</font></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686.445919px;top:365.755394px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">sПравильно</font></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:704.502966px;top:377.311999px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">sLeft</font></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664.777443px;top:365.755394px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o2</font></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337.471762px;top:401.247780px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">j1</font></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399.090750px;top:401.964342px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">t</font></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437.258525px;top:520.325014px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">w</font></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451.906912px;top:520.255447px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">l</font></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461.426221px;top:422.743251px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">j2</font></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483.484616px;top:518.880441px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">pLeft</font></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493.596550px;top:504.434662px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">pПравильно</font></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.597609px;top:519.602712px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n1</font></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557.157370px;top:521.769570px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n5</font></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576.659025px;top:399.702940px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o1</font></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591.826943px;top:376.589718px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">q</font></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604.105748px;top:366.477687px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n2</font></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:618.551369px;top:366.477687px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n3</font></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638.053012px;top:365.033111px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n4</font></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432.924811px;top:268.246539px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">120°</font></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391.754726px;top:297.138053px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">16°</font></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346.250954px;top:277.636264px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">105°</font></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392.477029px;top:210.463489px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">φ81</font></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409.811818px;top:197.462318px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">φ11.5</font></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372.975419px;top:310.861517px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">5°</font></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377.309105px;top:352.754223px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">φ81</font></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441.592227px;top:307.250072px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">e</font></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694.391032px;top:228.520691px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1.3°</font></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643.831271px;top:274.747113px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o2</font></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679.242184px;top:320.998322px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">[Раздел BB]");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376.879264px;top:175.546069px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">[Раздел АА]</font></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28.446729px;top:30.613805px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Отверстие для крепления переднего подрамника φ20 (спереди)<br>Отверстие для крепления переднего подрамника φ16 (сзади)<br>Отверстие для крепления опоры двигателя φ11 (спереди внутри)<br>Отверстие для крепления опоры двигателя φ11 (сзади)<br>Подвеска двигателя Монтажное отверстие φ11 (спереди снаружи)<br>Монтажное отверстие опоры трансмиссии φ13 (снизу спереди)<br>Монтажное отверстие опоры трансмиссии φ13 (снизу сзади)<br>Монтажное отверстие опоры трансмиссии φ13 (сверху)<br>Монтажное отверстие верхней реактивной тяги φ13×21(сверху)<br>Верхнее монтажное отверстие реактивной штанги φ14,5×19,5(снизу)<br>Центральное отверстие основания переднего амортизатора φ81<br>Контрольное отверстие передней боковой опоры φ25(внутри)<br>Контроль передней боковой опоры Отверстие φ25 (снаружи)<br>Отверстие опорной рамы передней стороны φ16<br>Отверстие опорной панели передней пола φ50<br>Спереди Отверстие для отсчета панели пола φ25 (спереди)<br>Передняя часть Отверстие для отсчета панели пола φ25 (сзади)<br>Передняя часть Отверстие для отсчета панели пола φ26.3 (сзади)<br>Передняя часть Отверстие для отсчета рамы пола φ25 (спереди)<br>Спереди Отверстие для отсчета рамы пола φ25 (заднее)<br>Отверстие для отсчета поперечины переднего пола φ20<br>Отверстие для крепления опоры топливного бака φ15<br>Нижнее отверстие для отсчета поперечины заднего конца φ20<br>Отверстие для отсчета рамы заднего пола φ20 (переднее) <br>Крепежное отверстие кронштейна балки заднего моста φ15 (спереди)<br>Крепежное отверстие кронштейна балки заднего моста φ17 (сзади)<br>Контрольное отверстие основания пружины задней подвески φ9<br>Крепежное отверстие кронштейна балки заднего моста φ15 (снаружи)< br>Отверстие для внутреннего удлинения четверти φ15<br>Основание заднего амортизатора Центральное отверстие φ26.4 Задняя колесная арка B опорное отверстие φ20");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724.726891px;top:29.169229px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Контрольное отверстие компрессора опоры топливного бака φ15 (справа)<br>Контрольное отверстие компрессора опоры топливного бака φ15 (слева)<br>Контрольное отверстие задней напольной панели φ20 (сзади)<br>Монтажное отверстие ремня крепления топливного бака φ13<br>Задний пол Отверстие для опорной поперечины φ15 (справа)<br>Отверстие для опорной поперечины заднего пола φ15 (слева)<br>Отверстие для опорной удлинительной поперечины B переднего пола φ20<br>Отверстие для опорной поперечины среднего пола φ20<br>Средняя поперечина пола Контрольное отверстие φ25<br>Контрольное отверстие задней нижней рамы φ25<br>Контрольное отверстие панели направляющей задней двери φ9</font></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:11.834235px;top:31.336093px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a1<br>a2<br>b1<br>b2<br>b3<br>c1<br>c2<br>c3<br>d1<br>d2<br>e<br>f1<br>f2<br>g<br>h1<br>h2<br>h3<br>h4<br>j1<br>j2<br>k<br>l<br>m<br>n1<br>n2<br>n3<br>n4<br>n5<br>o1<br>o2<br>o3</font></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709.558962px;top:29.169229px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">p вправо<br>p влево<br>q<br>r<br>s вправо<br>s влево<br>t<br>u вправо<br>u влево<br>v<br>w</ br> шрифт></nobr>");
write("</p>");
write("<v:line id=\"bl1_1\" from=\"57,465\" to=\"56,453\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_1\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"536\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_2\" from=\"46,464\" to=\"45,452\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_2\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"660\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_3\" from=\"67,465\" to=\"66,453\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_3\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"473\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_4\" from=\"78,465\" to=\"77,453\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_4\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"430\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_5\" from=\"88,465\" to=\"87,453\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_5\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"333\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_6\" from=\"97,465\" to=\"96,453\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_6\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"307\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_7\" from=\"107,465\" to=\"106,453\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_7\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"306\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_8\" from=\"127,492\" to=\"126,484\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_8\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"18\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_9\" from=\"258,495\" to=\"257,487\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_9\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"25\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_10\" from=\"787,451\" to=\"786,439\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_10\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"415\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_11\" from=\"777,465\" to=\"776,453\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_11\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"258\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_12\" from=\"767,459\" to=\"766,455\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_12\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_13\" from=\"343,501\" to=\"342,493\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_13\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"18\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_14\" from=\"361,496\" to=\"360,492\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_14\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"8\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_15\" from=\"408,497\" to=\"407,493\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_15\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"6\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_16\" from=\"455,499\" to=\"454,491\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_16\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"18\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_17\" from=\"570,494\" to=\"569,486\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_17\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"30\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_18\" from=\"583,499\" to=\"582,487\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_18\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"143\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_19\" from=\"597,494\" to=\"596,486\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_19\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"55\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_20\" from=\"611,494\" to=\"610,486\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_20\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"23\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_21\" from=\"629,494\" to=\"628,486\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_21\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"71\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_22\" from=\"655,499\" to=\"654,488\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_22\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"111\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_23\" from=\"681,494\" to=\"680,486\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_23\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"94\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_24\" from=\"447,444\" to=\"446,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_24\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"40\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_25\" from=\"486,444\" to=\"485,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_25\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"73\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_26\" from=\"496,444\" to=\"495,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_26\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"77\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_27\" from=\"514,444\" to=\"513,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_27\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"10\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_28\" from=\"525,444\" to=\"524,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_28\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"36\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_29\" from=\"535,444\" to=\"534,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_29\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"38\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_30\" from=\"546,444\" to=\"545,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_30\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"38\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_31\" from=\"433,444\" to=\"432,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_31\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"27\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_32\" from=\"419,444\" to=\"418,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_32\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"95\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_33\" from=\"376,449\" to=\"375,437\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_33\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"100\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_34\" from=\"352,444\" to=\"351,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_34\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"97\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_35\" from=\"308,439\" to=\"307,431\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_35\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"64\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_36\" from=\"576,515\" to=\"575,507\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_36\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"n5\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_37\" from=\"588,515\" to=\"587,511\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_37\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"q\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_38\" from=\"601,514\" to=\"600,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_38\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"n3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_39\" from=\"616,514\" to=\"615,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_39\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"n2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_40\" from=\"633,514\" to=\"632,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_40\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"n4\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_41\" from=\"659,534\" to=\"658,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_41\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"s右、s左\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_42\" from=\"684,510\" to=\"683,507\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_42\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"v\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_43\" from=\"790,414\" to=\"789,406\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_43\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"o2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_44\" from=\"780,436\" to=\"779,428\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_44\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"o3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_45\" from=\"771,493\" to=\"770,483\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_45\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"m2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_46\" from=\"262,525\" to=\"261,508\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_46\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"a2、g\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_47\" from=\"348,512\" to=\"347,507\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_47\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"j1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_48\" from=\"365,509\" to=\"364,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_48\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"k\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_49\" from=\"412,508\" to=\"411,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_49\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"t\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_50\" from=\"460,512\" to=\"459,507\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_50\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"j2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_51\" from=\"449,422\" to=\"448,421\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_51\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"l\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_52\" from=\"488,422\" to=\"487,414\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_52\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"p左\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_53\" from=\"501,422\" to=\"500,406\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_53\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"p右\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_54\" from=\"517,422\" to=\"516,414\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_54\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"n1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_55\" from=\"528,421\" to=\"527,419\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_55\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"r\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_56\" from=\"538,422\" to=\"537,406\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_56\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"u右\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_57\" from=\"436,421\" to=\"435,416\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_57\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"w\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_58\" from=\"422,423\" to=\"421,415\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_58\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"h4\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_59\" from=\"382,422\" to=\"381,414\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_59\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"h3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_60\" from=\"354,422\" to=\"353,414\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_60\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"h2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_61\" from=\"311,423\" to=\"310,415\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_61\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"h1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_62\" from=\"131,507\" to=\"130,499\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_62\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"a1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_63\" from=\"57,416\" to=\"56,408\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_63\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"d1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_64\" from=\"46,395\" to=\"45,391\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_64\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"e\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_65\" from=\"67,423\" to=\"66,415\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_65\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"d2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_66\" from=\"78,429\" to=\"77,422\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_66\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"c3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_67\" from=\"93,512\" to=\"92,478\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_67\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"b1、b2、b3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_68\" from=\"97,443\" to=\"96,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_68\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"c2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_69\" from=\"107,443\" to=\"106,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_69\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"c1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_70\" from=\"298,502\" to=\"297,494\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_70\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"32\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_71\" from=\"302,526\" to=\"301,509\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_71\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"f1、f2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_72\" from=\"549,422\" to=\"548,414\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_72\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"u左\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_73\" from=\"572,346\" to=\"571,338\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_73\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"o1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_74\" from=\"567,377\" to=\"566,365\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_74\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"336\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("</v:group>");
}