with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:546.07px;\" coordsize=\"950.00,546.07\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:546.07px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/106_2.0_jpn_15145738_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:546.07px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13.986068px;top:3.167216px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Единица измерения: мм/φ: указывает диаметр отверстия</font></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234.749232px;top:537.024704px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">Линия отсчета</font></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:508.178114px;top:536.302292px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">2000</font></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62.323104px;top:227.112834px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">Центральная линия</font></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198.676817px;top:357.145790px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">101</font></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198.676817px;top:368.704265px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">154</font></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266.492956px;top:357.145790px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">57</font></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203.726963px;top:388.931613px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">475</font></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256.392685px;top:388.931613px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">425</font></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:268.657302px;top:398.322874px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">457</font></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284.529174px;top:408.436548px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">651</font></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296.793769px;top:418.550222px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">848</font></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296.072335px;top:428.663896px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">900</font></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302.565371px;top:439.499981px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">907</font></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.665642px;top:449.613655px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1160</font></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324.208825px;top:459.727328px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1318</font></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331.423294px;top:469.841002px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1343</font></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333.587640px;top:479.954676px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1425</font></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340.802132px;top:490.068350px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1484</font></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348.016601px;top:500.182023px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1594</font></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539.200426px;top:358.590591px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">83</font></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532.707346px;top:368.704265px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">323</font></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530.543001px;top:379.540351px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">353</font></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534.150258px;top:389.654024px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">363</font></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522.607097px;top:399.045286px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">380</font></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534.150258px;top:409.158960px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">398</font></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540.643293px;top:419.272634px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">430</font></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544.250506px;top:429.386307px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">483</font></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544.971984px;top:440.222393px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">499</font></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544.250506px;top:451.058478px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">518</font></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567.336872px;top:461.172151px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">787</font></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577.437121px;top:471.285825px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">972</font></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577.437121px;top:480.677087px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1003</font></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578.880032px;top:490.790761px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1013</font></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597.637707px;top:500.904434px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1292</font></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604.852220px;top:511.018108px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1350</font></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:627.938541px;top:521.131782px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1710</font></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199.398272px;top:83.354196px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">356</font></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218.155924px;top:94.912676px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">220</font></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254.949796px;top:105.026349px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">144</font></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254.949796px;top:115.862435px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">136</font></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109.217234px;top:337.640833px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c1</font></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129.417788px;top:349.199330px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c2</font></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154.668476px;top:359.313003px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c3</font></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540.635856px;top:76.852550px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">xПравильно</font></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674.111227px;top:76.852553px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">y</font></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446.000920px;top:94.912681px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">w</font></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138.075169px;top:136.089782px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a1</font></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144.568194px;top:120.196860px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b1</font></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153.427264px;top:104.303948px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b3</font></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179.919175px;top:70.350903px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d2</font></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170.540338px;top:79.742171px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d1</font></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361.724129px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">j1</font></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376.153091px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h2</font></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334.309095px;top:93.467870px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">g</font></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345.852256px;top:94.396675px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h1</font></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303.286827px;top:79.742171px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a2</font></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.323023px;top:94.912676px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">f2</font></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284.529174px;top:61.682042px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">e</font></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392.746376px;top:94.396675px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">k</font></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402.846669px;top:94.396675px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h3</font></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426.654468px;top:94.396675px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h4</font></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416.554219px;top:94.087076px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">t</font></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459.841082px;top:94.396675px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">l</font></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469.941375px;top:94.396675px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">j2</font></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495.192086px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">pПравильно</font></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511.785370px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n1</font></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527.657266px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">r</font></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525.492876px;top:76.852553px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">uПравильно</font></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552.186454px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n2</font></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579.645677px;top:93.467870px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">q</font></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564.451093px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n5</font></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.537457px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o1</font></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:599.802052px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n3</font></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614.952469px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n4</font></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634.431577px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o2</font></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658.960810px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">sПравильно</font></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.704512px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">v</font></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706.576364px;top:94.190276px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o3</font></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310.501319px;top:94.912676px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">f1</font></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773.972378px;top:102.859138px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">m</font></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26.250689px;top:24.116967px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Отверстие для крепления переднего подрамника φ20 (спереди)<br>Отверстие для крепления переднего подрамника φ16 (сзади)<br>Отверстие для крепления опоры двигателя φ11 (спереди внутри)<br>Отверстие для крепления опоры двигателя φ11 (сзади)<br>Подвеска двигателя Монтажное отверстие φ11 (переднее внешнее)<br>Крепление трансмиссии<br>Монтажное отверстие φ13 (нижнее переднее)<br>Крепление трансмиссии<br>Монтажное отверстие φ13 (нижнее заднее)<br>Крепление трансмиссии<br>Монтажное отверстие φ13 (верхнее )<br>Верхняя реактивная штанга<br>Монтажное отверстие φ13×21(нижнее)<br>Верхняя реактивная штанга<br>Монтажное отверстие φ14,5×19,5(верхнее)</font></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:27.006548px;top:368.704264px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Центральное отверстие основания переднего амортизатора φ81<br>Контрольное отверстие переднего аутригера φ25 (внутреннее)<br>Контрольное отверстие переднего аутригера φ25 (внешнее)<br>Контрольное отверстие передней боковой рамы φ16<br>Контрольное отверстие передней панели пола φ50< br>Контрольное отверстие передней панели пола φ25 (спереди)<br>Контрольное отверстие передней панели пола φ25 (сзади)<br>Контрольное отверстие передней панели пола φ26.3 (сзади)<br>Контрольное отверстие передней рамы пола φ25 (спереди)< br>Контрольное отверстие рамы переднего пола φ25 (заднее)<br>Контрольное отверстие поперечины переднего пола φ20<br>Монтажное отверстие опоры топливного бака φ15<br>Нижнее контрольное отверстие поперечины заднего конца φ20<br>Контрольное отверстие рамы заднего пола φ20 (Передняя) Отверстие для крепления кронштейна балки заднего моста φ15 (Передняя) Балка заднего моста Отверстие для крепления кронштейна φ17 (заднее)<br>Контрольное отверстие основания пружины задней подвески □15<br>Крепежное отверстие кронштейна балки заднего моста φ15 (внешнее)<br>Контрольное отверстие внутреннего удлинения четверти φ15<br>Центральное отверстие основания заднего амортизатора φ26. 4 Задняя колесная арка B опорное отверстие φ20");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:11.821724px;top:24.116967px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a1<br>a2<br>b1<br>b2<br>b3<br>c1<br><br>c2<br><br>c3<br><br>d1<br><br>d2</font></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:11.836061px;top:368.704264px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">e<br>f1<br>f2<br>g<br>h1<br>h2<br>h3<br>h4<br>j1<br>j2<br>k<br>l<br>m<br>n1<br>n2<br>n3<br>n4<br>n5<br>o1<br>o2<br>o3<br></font></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490.067570px;top:367.981859px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">pLeft</font></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548.579197px;top:347.754507px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">u Левый</font></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532.707346px;top:347.754507px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">xLeft</font></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675.554095px;top:367.981854px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">sLeft</font></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.888440px;top:83.354197px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b1、b3</font></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234.336522px;top:94.912681px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b2</font></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228.977652px;top:105.026349px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d1</font></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228.977652px;top:115.862435px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d2</font></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231.863453px;top:357.145790px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c3</font></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229.699107px;top:368.704265px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c2</font></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245.570959px;top:357.386587px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">e</font></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:183.526410px;top:388.931613px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a1</font></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.036139px;top:388.931613px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">f1、f2</font></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297.515225px;top:398.322874px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">g</font></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323.487369px;top:408.436548px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h1</font></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350.902403px;top:418.550222px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">j1</font></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357.395438px;top:428.663896px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h2</font></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362.445563px;top:439.499981px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">k</font></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389.860597px;top:449.613655px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h3</font></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416.382353px;top:459.727324px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">t</font></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419.271969px;top:470.563402px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">z</font></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428.818813px;top:479.954676px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h4</font></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440.944092px;top:490.790749px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">w</font></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455.512391px;top:500.182023px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">j2</font></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519.721274px;top:358.590591px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n1</font></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557.236622px;top:368.704265px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">r</font></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550.022109px;top:379.540351px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">u Левый</font></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552.907932px;top:388.931613px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">uПравильно</font></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:541.364771px;top:399.045286px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">xСправа, слева</font></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561.565269px;top:409.158960px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n2</font></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563.729615px;top:419.272634px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n5</font></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575.311252px;top:429.386304px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">q</font></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575.994253px;top:440.222393px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o1</font></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575.272775px;top:451.058478px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n3</font></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613.509557px;top:461.172151px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n4</font></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639.481702px;top:471.285825px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o2</font></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641.646047px;top:480.677087px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">sПравильно</font></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.367481px;top:490.790761px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">осталось</font></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:692.147424px;top:500.904434px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">v</font></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693.590336px;top:511.018108px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o3</font></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745.076214px;top:521.131769px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">m</font></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:797.089309px;top:350.644134px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Передняя поперечина пола B <br>Контрольное отверстие удлинителя φ20<br>Контрольное отверстие средней поперечины пола φ20 (справа)<br>Контрольное отверстие средней поперечины пола φ25 (слева)<br>Контрольное отверстие задней нижней рамы φ25<br >Опорное отверстие направляющей задней двери φ20<br>Переднее крепление заднего дифференциала<br>Крепежное отверстие φ13 (справа)<br>Переднее крепление заднего дифференциала<br>Крепежное отверстие φ13 (слева)<br>Заднее крепление заднего дифференциала<br> Монтажное отверстие φ13<br>Центральный подшипник вала гребного винта<br>Монтажное отверстие φ11</font></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781.196419px;top:350.644134px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">t<br><br>u вправо<br>u влево<br>v<br>w<br>x вправо<br><br>x влево<br><br>y<br><br>z </font></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:779.751611px;top:29.173804px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">p вправо<br><br>p влево<br><br>q<br>r<br>s вправо<br>s влево</font></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795.644501px;top:29.173804px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Опорный элемент топливного бака<br>Контрольное отверстие φ15 (справа)<br>Опорный элемент топливного бака<br>Контрольное отверстие φ15 (слева)<br>Контрольное отверстие задней напольной панели φ25 (слева)<br>Отверстие для крепления ремня безопасности топливного бака 13φ<br>Контрольное отверстие задней поперечины пола φ15 (справа)<br>Контрольное отверстие задней поперечины пола φ15 (слева)<br></font></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:888.381329px;top:227.112834px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">Центральная линия</font></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480.041668px;top:511.018108px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1886</font></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489.420483px;top:499.459612px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">pLeft</font></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480.041668px;top:521.131782px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1953</font></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500.242166px;top:521.131782px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">pПравильно</font></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263.955089px;top:378.817937px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">389</font></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224.222864px;top:378.817937px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">205</font></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205.440358px;top:378.817937px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c1</font></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283.460000px;top:378.817937px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a2</font></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162.096112px;top:92.023060px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b2</font></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420.716777px;top:75.407739px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">z</font></nobr>");
write("</p>");
write("<v:line id=\"bl1_1\" from=\"116,226\" to=\"115,211\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_1\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1104\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_2\" from=\"137,267\" to=\"136,255\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_2\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"980\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_3\" from=\"126,205\" to=\"125,193\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_3\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"525\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_4\" from=\"146,205\" to=\"145,193\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_4\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"479\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_5\" from=\"229,204\" to=\"228,192\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_5\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"477\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_6\" from=\"442,181\" to=\"441,169\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_6\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"451\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_7\" from=\"412,226\" to=\"411,214\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_7\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"605\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_8\" from=\"421,210\" to=\"420,198\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_8\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"173\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_9\" from=\"401,226\" to=\"400,214\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_9\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"624\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_10\" from=\"370,166\" to=\"369,154\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_10\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"824\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_11\" from=\"382,226\" to=\"381,214\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_11\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"982\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_12\" from=\"392,226\" to=\"391,214\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_12\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"884\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_13\" from=\"351,226\" to=\"350,214\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_13\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"832\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_14\" from=\"341,226\" to=\"340,214\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_14\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"480\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_15\" from=\"360,166\" to=\"359,154\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_15\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"620\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_16\" from=\"323,228\" to=\"322,212\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_16\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1236\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_17\" from=\"191,267\" to=\"190,255\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_17\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"434\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_18\" from=\"181,267\" to=\"180,255\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_18\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"454\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_19\" from=\"507,222\" to=\"506,210\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_19\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"228\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_20\" from=\"507,255\" to=\"506,243\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_20\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"250\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_21\" from=\"720,204\" to=\"719,192\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_21\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"146\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_22\" from=\"774,227\" to=\"773,215\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_22\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"474\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_23\" from=\"784,227\" to=\"783,215\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_23\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"970\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_24\" from=\"728,285\" to=\"727,273\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_24\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"234\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_25\" from=\"815,227\" to=\"814,211\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_25\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1280\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_26\" from=\"805,227\" to=\"804,212\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_26\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1119\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_27\" from=\"795,227\" to=\"794,215\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_27\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"984\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_28\" from=\"836,227\" to=\"835,211\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_28\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1388\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_29\" from=\"826,227\" to=\"825,211\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_29\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1370\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_30\" from=\"846,227\" to=\"845,211\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_30\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1416\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_31\" from=\"577,251\" to=\"576,243\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_31\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"76\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_32\" from=\"550,226\" to=\"549,214\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_32\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"451\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_33\" from=\"597,226\" to=\"596,214\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_33\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"718\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_34\" from=\"564,184\" to=\"563,172\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_34\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"102\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_35\" from=\"621,273\" to=\"620,261\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_35\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"150\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_36\" from=\"608,226\" to=\"607,214\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_36\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"590\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_37\" from=\"645,215\" to=\"644,203\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_37\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"313\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_38\" from=\"539,226\" to=\"538,214\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_38\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"984\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_39\" from=\"273,226\" to=\"272,214\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_39\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"940\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_40\" from=\"284,226\" to=\"283,214\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_40\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"562\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_41\" from=\"228,267\" to=\"227,255\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_41\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"439\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_42\" from=\"314,226\" to=\"313,211\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_42\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"1100\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_43\" from=\"207,204\" to=\"206,192\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_43\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"474\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("</v:group>");
}