with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:546.07px;\" coordsize=\"950.00,546.07\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:546.07px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/107_2.0_jpn_15145739_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:546.07px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13.278799px;top:6.778303px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Единица: мм/φ: диаметр отверстия</font></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545.600874px;top:531.881633px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">xСправа, слева</font></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.933487px;top:519.602727px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">uПравильно</font></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522.487839px;top:519.602727px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">u Левый</font></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519.598712px;top:505.156977px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">r</font></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648.887261px;top:386.701747px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;background-color:#ffffff;left:648.887261px;top:427.872183px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;background-color:#ffffff;left:248.020556px;top:396.091495px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.020556px;top:356.365646px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142.571243px;top:358.391596px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b1<br>b3</font></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177.821120px;top:486.443919px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c1</font></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168.469120px;top:350.478259px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b2</font></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221.296114px;top:486.377482px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c2</font></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200.841458px;top:486.443919px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c3</font></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200.122075px;top:341.845528px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d1</font></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228.178088px;top:339.687346px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d2</font></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281.412605px;top:351.917047px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">e</font></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274.744999px;top:401.147526px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a2</font></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274.744999px;top:519.602712px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">f1、<br>f2</font></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291.483977px;top:400.116482px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">g</font></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369.896999px;top:400.116482px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">k</font></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157.012980px;top:486.377482px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a1</font></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728.870209px;top:391.483795px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o3</font></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322.417561px;top:400.835920px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h1</font></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385.723450px;top:400.835920px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h3</font></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.825606px;top:400.835920px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h2</font></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422.090618px;top:519.602712px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h4</font></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702.252983px;top:498.673621px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">v </font></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766.619266px;top:400.425220px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">m</font></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687.168222px;top:365.033122px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">sПравильно</font></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:704.502966px;top:376.589728px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">sLeft</font></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665.499747px;top:365.033122px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o2</font></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648.164957px;top:530.437046px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">y</font></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336.085887px;top:400.116482px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">j1</font></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397.953034px;top:400.835920px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">t</font></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408.367232px;top:400.425220px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">z</font></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437.980808px;top:519.602727px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">w</font></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450.981903px;top:519.602712px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">l</font></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460.539541px;top:421.698352px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">j2</font></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505.875351px;top:519.602712px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n1</font></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556.435111px;top:521.047299px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n5</font></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577.381283px;top:398.258353px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o1</font></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588.937814px;top:375.145143px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">q</font></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604.828007px;top:365.033122px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n2</font></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619.273672px;top:365.033122px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n3</font></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634.441596px;top:365.033122px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n4</font></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432.924811px;top:268.246539px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">120°</font></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391.032467px;top:297.138053px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">16°</font></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345.528673px;top:277.636264px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">105°</font></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391.754726px;top:209.741217px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">φ81</font></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409.089514px;top:196.740025px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">φ11.5</font></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372.253116px;top:310.861517px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">5°</font></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376.586801px;top:352.754223px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">φ81</font></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441.116136px;top:307.314562px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">e</font></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694.391032px;top:227.798397px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1.3°</font></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643.982769px;top:274.222406px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">o2</font></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679.232668px;top:319.544286px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">[Раздел BB]");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375.652101px;top:173.507106px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">[Раздел АА]</font></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26.279882px;top:28.446941px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Отверстие для крепления переднего подрамника φ20 (спереди)<br>Отверстие для крепления переднего подрамника φ16 (сзади)<br>Отверстие для крепления опоры двигателя φ11 (спереди внутри)<br>Отверстие для крепления опоры двигателя φ11 (сзади)<br>Подвеска двигателя Монтажное отверстие φ11 (спереди снаружи)<br>Монтажное отверстие опоры трансмиссии φ13 (снизу спереди)<br>Монтажное отверстие опоры трансмиссии φ13 (снизу сзади)<br>Монтажное отверстие опоры трансмиссии φ13 (сверху)<br>Монтажное отверстие верхней реактивной тяги φ13×21(сверху)<br>Верхнее монтажное отверстие реактивной штанги φ14,5×19,5(снизу)<br>Центральное отверстие основания переднего амортизатора φ81<br>Контрольное отверстие передней боковой опоры φ25(внутри)<br>Контроль передней боковой опоры Отверстие φ25 (снаружи)<br>Отверстие опорной рамы передней стороны φ16<br>Отверстие опорной панели передней пола φ50<br>Спереди Отверстие для отсчета панели пола φ25 (спереди)<br>Передняя часть Отверстие для отсчета панели пола φ25 (сзади)<br>Передняя часть Отверстие для отсчета панели пола φ26.3 (сзади)<br>Передняя часть Отверстие для отсчета рамы пола φ25 (спереди)<br>Спереди Отверстие для отсчета рамы пола φ25 (заднее)<br>Отверстие для отсчета поперечины переднего пола φ20<br>Отверстие для крепления опоры топливного бака φ15<br>Нижнее отверстие для отсчета поперечины заднего конца φ20<br>Отверстие для отсчета рамы заднего пола φ20 (переднее) <br>Крепежное отверстие кронштейна балки заднего моста φ15 (спереди)<br>Крепежное отверстие кронштейна балки заднего моста φ17 (сзади)<br>Контрольное отверстие основания пружины задней подвески □15<br>Крепежное отверстие кронштейна балки заднего моста φ15 (снаружи) <br>Отверстие для внутреннего удлинения четверти φ15<br>Основание заднего амортизатора Центральное отверстие φ26.4 Задняя колесная арка B опорное отверстие φ20");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724.726891px;top:27.002365px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Контрольное отверстие компрессора опоры топливного бака φ15 (справа)<br>Контрольное отверстие компрессора опоры топливного бака φ15 (слева)<br>Контрольное отверстие поперечины среднего пола φ25 (слева)<br>Крепежное отверстие ремня крепления топливного бака φ13<br>Задняя часть Отверстие для отсчета поперечины пола φ15 (справа)<br>Отверстие для отсчета задней поперечины пола φ15 (слева)<br>Отверстие для отсчета удлинения передней поперечины пола B φ20<br>Отверстие для отсчета средней поперечины пола φ20 (справа)<br> Отверстие для опоры поперечины среднего пола φ25 (слева)<br>Отверстие для опоры задней нижней рамы φ25<br>Отверстие для опоры направляющей задней двери φ20<br>Отверстие для установки переднего крепления заднего дифференциала φ13 (справа)<br>Установка переднего крепления заднего дифференциала Отверстие φ13 (левое) Задний дифференциал Задний Монтажное отверстие крепления φ13<br>Монтажное отверстие центрального подшипника вала гребного винта φ11</font></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:9.667388px;top:28.446941px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a1<br>a2<br>b1<br>b2<br>b3<br>c1<br>c2<br>c3<br>d1<br>d2<br>e<br>f1<br>f2<br>g<br>h1<br>h2<br>h3<br>h4<br>j1<br>j2<br>k<br>l<br>m<br>n1<br>n2<br>n3<br>n4<br>n5<br>o1<br>o2<br>o3</font></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709.558962px;top:27.002365px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">p вправо<br>p влево<br>q<br>r<br>s вправо<br>s влево<br>t<br>u вправо<br>u влево<br>v<br>w<br >xВправо<br>xВлево<br>y<br>z</font></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483.484616px;top:518.158169px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">pLeft</font></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493.596550px;top:503.712390px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">pПравильно</font></nobr>");
write("</p>");
write("<v:line id=\"bl1_1\" from=\"56,464\" to=\"55,452\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_1\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"536\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_2\" from=\"46,463\" to=\"45,451\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_2\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"660\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_3\" from=\"66,464\" to=\"65,452\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_3\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"473\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_4\" from=\"77,464\" to=\"76,452\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_4\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"430\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_5\" from=\"87,464\" to=\"86,452\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_5\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"333\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_6\" from=\"96,464\" to=\"95,452\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_6\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"307\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_7\" from=\"106,464\" to=\"105,452\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_7\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"306\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_8\" from=\"117,494\" to=\"116,482\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_8\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"158\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_9\" from=\"128,491\" to=\"127,483\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_9\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"18\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_10\" from=\"259,497\" to=\"258,489\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_10\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"25\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_11\" from=\"787,454\" to=\"786,442\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_11\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"415\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_12\" from=\"777,468\" to=\"776,456\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_12\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"258\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_13\" from=\"767,460\" to=\"766,456\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_13\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_14\" from=\"341,500\" to=\"340,492\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_14\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"18\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_15\" from=\"359,496\" to=\"358,492\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_15\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"8\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_16\" from=\"407,497\" to=\"406,493\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_16\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"6\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_17\" from=\"419,496\" to=\"418,492\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_17\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_18\" from=\"454,498\" to=\"453,490\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_18\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"18\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_19\" from=\"570,494\" to=\"569,486\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_19\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"30\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_20\" from=\"583,498\" to=\"582,486\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_20\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"143\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_21\" from=\"596,494\" to=\"595,486\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_21\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"55\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_22\" from=\"611,494\" to=\"610,486\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_22\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"23\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_23\" from=\"629,494\" to=\"628,486\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_23\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"71\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_24\" from=\"655,498\" to=\"654,487\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_24\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"111\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_25\" from=\"681,494\" to=\"680,486\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_25\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"94\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_26\" from=\"446,443\" to=\"445,435\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_26\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"40\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_27\" from=\"486,443\" to=\"485,435\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_27\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"73\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_28\" from=\"496,443\" to=\"495,435\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_28\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"77\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_29\" from=\"513,443\" to=\"512,435\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_29\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"10\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_30\" from=\"525,443\" to=\"524,435\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_30\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"36\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_31\" from=\"535,443\" to=\"534,435\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_31\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"38\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_32\" from=\"546,443\" to=\"545,435\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_32\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"38\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_33\" from=\"432,443\" to=\"431,435\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_33\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"27\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_34\" from=\"419,443\" to=\"418,435\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_34\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"95\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_35\" from=\"375,448\" to=\"374,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_35\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"100\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_36\" from=\"350,443\" to=\"349,435\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_36\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"97\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_37\" from=\"307,438\" to=\"306,430\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_37\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"64\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_38\" from=\"575,514\" to=\"574,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_38\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"n5\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_39\" from=\"587,514\" to=\"586,511\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_39\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"ｑ\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_40\" from=\"601,513\" to=\"600,505\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_40\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"n3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_41\" from=\"616,513\" to=\"615,505\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_41\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"n2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_42\" from=\"633,513\" to=\"632,505\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_42\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"n4\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_43\" from=\"659,533\" to=\"658,505\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_43\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"s右、s左\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_44\" from=\"684,509\" to=\"683,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_44\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"v\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_45\" from=\"791,414\" to=\"790,406\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_45\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"o2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_46\" from=\"780,435\" to=\"779,427\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_46\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"o3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_47\" from=\"771,489\" to=\"770,483\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_47\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"m\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_48\" from=\"262,524\" to=\"261,507\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_48\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"a2、g\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_49\" from=\"346,511\" to=\"345,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_49\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"j1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_50\" from=\"364,509\" to=\"363,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_50\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"k\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_51\" from=\"411,507\" to=\"410,505\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_51\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"t\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_52\" from=\"421,509\" to=\"420,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_52\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"z\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_53\" from=\"459,511\" to=\"458,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_53\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"j2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_54\" from=\"447,421\" to=\"446,420\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_54\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"l\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_55\" from=\"488,422\" to=\"487,414\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_55\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"p左\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_56\" from=\"500,421\" to=\"499,405\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_56\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"p右\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_57\" from=\"517,421\" to=\"516,413\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_57\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"n1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_58\" from=\"528,421\" to=\"527,419\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_58\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"r\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_59\" from=\"539,421\" to=\"538,405\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_59\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"u右\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_60\" from=\"564,421\" to=\"563,397\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_60\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"x右、左\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_61\" from=\"433,421\" to=\"432,416\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_61\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"w\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_62\" from=\"419,422\" to=\"418,414\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_62\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"h4\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_63\" from=\"381,421\" to=\"380,413\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_63\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"h3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_64\" from=\"355,421\" to=\"354,413\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_64\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"h2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_65\" from=\"312,422\" to=\"311,414\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_65\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"h1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_66\" from=\"121,507\" to=\"120,499\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_66\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"a3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_67\" from=\"132,507\" to=\"131,499\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_67\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"a1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_68\" from=\"56,414\" to=\"55,406\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_68\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"d1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_69\" from=\"46,392\" to=\"45,388\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_69\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"e\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_70\" from=\"66,422\" to=\"65,414\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_70\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"d2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_71\" from=\"77,428\" to=\"76,421\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_71\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"c3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_72\" from=\"91,512\" to=\"90,478\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_72\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"b1、b2、b3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_73\" from=\"96,442\" to=\"95,435\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_73\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"c2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_74\" from=\"106,442\" to=\"105,435\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_74\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"c1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_75\" from=\"572,345\" to=\"571,337\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_75\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"o1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_76\" from=\"567,376\" to=\"566,364\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_76\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"336\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_77\" from=\"297,501\" to=\"296,493\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_77\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"32\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_78\" from=\"302,525\" to=\"301,508\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_78\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"f1、f2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_79\" from=\"639,494\" to=\"638,486\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_79\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"71\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_80\" from=\"643,509\" to=\"642,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_80\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"y\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_81\" from=\"561,444\" to=\"560,436\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_81\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"36\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_82\" from=\"549,421\" to=\"548,413\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_82\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"u左\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:4.5pt;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\"/>");
write("</v:line>");
write("</v:group>");
}