with(document) {
write("<v:group id=\"group6\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:983.36px;\" coordsize=\"950.00,983.36\">");
write("<v:rect id=\"rect6\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:983.36px;\">");
write("<img id=\"img6\" name=\"PrtImgId\" src=\"../img/25_3.0_jpn_15145862_3.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:983.36px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p6_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18.337765px;top:14.003277px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi6\" style=\"height:14px;\" src=\"../img/symbol/Gaiji00007.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p6_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567.366979px;top:259.620729px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi6\" style=\"height:14px;\" src=\"../img/symbol/Gaiji00005.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p6_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18.337765px;top:289.961707px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi6\" style=\"height:14px;\" src=\"../img/symbol/Gaiji00006.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p6_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16.892951px;top:649.719033px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi6\" style=\"height:14px;\" src=\"../img/symbol/Gaiji00008.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p6_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522.577754px;top:555.806479px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi6\" style=\"height:14px;\" src=\"../img/symbol/Gaiji00009.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p6_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37.120343px;top:40.009831px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Панель крыши<br>[0,7] 270 или 340<br>Передняя рейка крыши<br>[0,6] 270<br>Арка крыши C[0,6] 270<br>Задняя рейка крыши, комп: <br>・Верхняя[0,6 ] 270<br>・Нижний [0,8] 270<br>Арка крыши E [0,7] 270<br>Арка крыши F [0,9] 270<br>Арка крыши D [0,6] 270<br>Арка крыши B [1,2] 980<br>Крыша Арка A[0.6] 270</font></nobr>");
write("</p>");
write("<p id=\"p6_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18.337765px;top:40.009831px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a:<br><br>b:<br><br>c:<br>d:<br><br><br>e:<br>f:<br>g:<br>h:<br>j:</font></nobr>");
write("</p>");
write("<p id=\"p6_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18.337765px;top:320.302687px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a:<br><br>b:<br><br>c:</font></nobr>");
write("</p>");
write("<p id=\"p6_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713.293165px;top:801.423931px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Центральная стойка нижняя часть жесткости <br>[1.4] 590 <br>Центральная стойка жесткости<br>Усиление <br>[0.8] 590</font></nobr>");
write("</p>");
write("<p id=\"p6_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694.510586px;top:801.423931px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a:<br><br>b:</font></nobr>");
write("</p>");
write("<p id=\"p6_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34.230716px;top:681.504822px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Передняя стойка <br>Нижнее ребро жесткости <br>[1.4] 980, Zn <br>Боковое ребро жесткости порога <br>Усиление <br>[1.0] 270 <br>Боковое ребро жесткости порога <br>Усиление Заднее < br>[1.4 ] 980 <br>Боковой элемент жесткости порога <br>[1.2] 980, Zn <br>Передняя опора домкрата <br>[2.3] 590, Zn <br>Передняя стойка нижняя <br>Усиление < br>[2.3] 590</font></nobr>");
write("</p>");
write("<p id=\"p6_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16.892951px;top:681.504822px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a:<br><br><br>b:<br><br><br>c:<br><br><br>d:<br><br>e:<br><br>f:</font></nobr>");
write("</p>");
write("<p id=\"p6_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418.551166px;top:210.497239px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b</font></nobr>");
write("</p>");
write("<p id=\"p6_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496.571106px;top:245.172643px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a</font></nobr>");
write("</p>");
write("<p id=\"p6_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756.637576px;top:165.708173px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">g</font></nobr>");
write("</p>");
write("<p id=\"p6_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:844.771214px;top:136.812002px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">f</font></nobr>");
write("</p>");
write("<p id=\"p6_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.737980px;top:184.490685px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c</font></nobr>");
write("</p>");
write("<p id=\"p6_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795.647547px;top:149.815279px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">e</font></nobr>");
write("</p>");
write("<p id=\"p6_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674.283194px;top:203.273195px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h</font></nobr>");
write("</p>");
write("<p id=\"p6_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639.607666px;top:222.055707px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">j</font></nobr>");
write("</p>");
write("<p id=\"p6_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:879.446744px;top:118.029492px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d</font></nobr>");
write("</p>");
write("<p id=\"p6_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466.230019px;top:526.910308px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a</font></nobr>");
write("</p>");
write("<p id=\"p6_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707.513910px;top:395.432731px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b</font></nobr>");
write("</p>");
write("<p id=\"p6_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568.811793px;top:339.085199px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c</font></nobr>");
write("</p>");
write("<p id=\"p6_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643.942107px;top:300.075368px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a</font></nobr>");
write("</p>");
write("<p id=\"p6_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311.634950px;top:925.677465px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">f</font></nobr>");
write("</p>");
write("<p id=\"p6_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409.882283px;top:766.748525px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a</font></nobr>");
write("</p>");
write("<p id=\"p6_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654.055802px;top:769.638143px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a</font></nobr>");
write("</p>");
write("<p id=\"p6_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551.474028px;top:691.618482px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b</font></nobr>");
write("</p>");
write("<p id=\"p6_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447.447440px;top:902.560529px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b</font></nobr>");
write("</p>");
write("<p id=\"p6_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485.012597px;top:896.781294px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c</font></nobr>");
write("</p>");
write("<p id=\"p6_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405.547842px;top:917.008614px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d</font></nobr>");
write("</p>");
write("<p id=\"p6_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353.534549px;top:947.349593px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">e</font></nobr>");
write("</p>");
write("<p id=\"p6_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425.775234px;top:576.033798px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b</font></nobr>");
write("</p>");
write("<p id=\"p6_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237.949451px;top:573.144181px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c</font></nobr>");
write("</p>");
write("<p id=\"p6_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.497293px;top:454.669882px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d</font></nobr>");
write("</p>");
write("<p id=\"p6_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40.009971px;top:12.558468px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Комп. панели крыши</font></nobr>");
write("</p>");
write("<p id=\"p6_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589.039185px;top:259.620729px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Внешняя часть крыши</font></nobr>");
write("</p>");
write("<p id=\"p6_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38.565157px;top:649.719033px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Компьютер нижнего элемента жесткости передней стойки</font></nobr>");
write("</p>");
write("<p id=\"p6_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544.249960px;top:555.806479px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Центральная стойка, ребро жесткости</font></nobr>");
write("</p>");
write("<p id=\"p6_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311.634950px;top:486.455669px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a</font></nobr>");
write("</p>");
write("<p id=\"p6_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262.511284px;top:521.131073px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b</font></nobr>");
write("</p>");
write("<p id=\"p6_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40.009971px;top:289.961707px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Комплект верхних элементов жесткости передней стойки</font></nobr>");
write("</p>");
write("<p id=\"p6_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37.120343px;top:321.747496px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Верхнее ребро жесткости передней стойки<br>[1.0] 1500<br>Верхнее усиление передней стойки<br>[1.6] 980<br>Верхнее расширение передней стойки<br>[1.6] 980(только правая сторона)</font> < /нет>");
write("</p>");
write("<p id=\"p6_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:782.644224px;top:295.740942px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Крыша верхняя <br>Внешняя<br>[0.7] 270, Zn<br>Крыша нижняя <br>Внешняя<br>[0.7] 270, Zn<br>Крыша верхняя <br>Передняя наружная<br> [2.0] 590, Zn <br> Центральная стойка верхняя <br> Ребро жесткости <br> [1.6] 590</font></nobr>");
write("</p>");
write("<p id=\"p6_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.306459px;top:295.740942px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a:<br><br><br>b:<br><br><br>c:<br><br><br>d:</font></nobr>");
write("</p>");
write("</v:group>");
}