with(document) {
write("<div id=\"group9\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:1092.14px;\" coordsize=\"950.00,1092.14\">");
write("<div id=\"rect9\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:1092.14px;\">");
write("<img id=\"img9\" name=\"PrtImgId\" src=\"../img/25_3.0_jpn_15145865_3.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:1092.14px;border-color:#ffffff\">");
write("</div>");
write("<p id=\"p9_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756.637576px;top:13.521665px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi9\" style=\"height:14px;\" src=\"../img/symbol/Gaiji00007.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p9_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74.685500px;top:22.672119px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi9\" style=\"height:14px;\" src=\"../img/symbol/Gaiji00005.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p9_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730.630930px;top:198.938689px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi9\" style=\"height:14px;\" src=\"../img/symbol/Gaiji00005.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p9_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19.782578px;top:224.945232px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi9\" style=\"height:14px;\" src=\"../img/symbol/Gaiji00006.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p9_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343.420852px;top:331.861020px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi9\" style=\"height:14px;\" src=\"../img/symbol/Gaiji00008.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p9_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:18.337765px;top:639.605112px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi9\" style=\"height:14px;\" src=\"../img/symbol/Gaiji00009.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p9_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:779.754597px;top:14.003271px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Первый этаж <br>[0.65] 270</font></nobr>");
write("</p>");
write("<p id=\"p9_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310.190136px;top:557.251060px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">e</font></nobr>");
write("</p>");
write("<p id=\"p9_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674.283215px;top:248.062160px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a</font></nobr>");
write("</p>");
write("<p id=\"p9_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34.230716px;top:263.955047px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a:<br><br>b:<br><br>c:<br><br>d:<br><br>e:<br><br>f:</font></nobr>");
write("</p>");
write("<p id=\"p9_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594.818444px;top:275.513514px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b</font></nobr>");
write("</p>");
write("<p id=\"p9_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753.747949px;top:198.938689px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Комп. заплатка для переднего пола</font></nobr>");
write("</p>");
write("<p id=\"p9_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778.309782px;top:308.744092px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Передняя часть пола <br>[2.0] 780 <br>Передняя часть пола B <br>[1.4] 780</font></nobr>");
write("</p>");
write("<p id=\"p9_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760.972017px;top:308.744092px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a:<br><br>b:</font></nobr>");
write("</p>");
write("<p id=\"p9_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96.357706px;top:22.672119px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Комп. заплатка для переднего пола</font></nobr>");
write("</p>");
write("<p id=\"p9_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40.009971px;top:224.945232px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Передняя поперечина пола, передняя часть.");
write("</p>");
write("<p id=\"p9_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:51.568481px;top:263.955047px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Передняя поперечина пола A <br>[0.6] 270<br>Передний центральный кронштейн сиденья справа <br>[1.2] 270<br>Усилитель стояночного тормоза <br>[1.4] 270<br>Передний центральный кронштейн сиденья Левый <br>[1.2] 270<br>Кронштейн канистры <br>[1.4] 270<br>Перекладина передняя перегородка <br>[1.6] 270</font></nobr>");
write("</p>");
write("<p id=\"p9_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281.293862px;top:622.267417px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">f</font></nobr>");
write("</p>");
write("<p id=\"p9_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86.244009px;top:571.699139px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a</font></nobr>");
write("</p>");
write("<p id=\"p9_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274.069794px;top:486.455470px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d</font></nobr>");
write("</p>");
write("<p id=\"p9_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236.504637px;top:461.893735px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c</font></nobr>");
write("</p>");
write("<p id=\"p9_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175.822461px;top:466.228158px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b</font></nobr>");
write("</p>");
write("<p id=\"p9_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532.691451px;top:883.777655px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">e</font></nobr>");
write("</p>");
write("<p id=\"p9_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612.156204px;top:866.439959px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">f</font></nobr>");
write("</p>");
write("<p id=\"p9_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492.236665px;top:882.332847px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d</font></nobr>");
write("</p>");
write("<p id=\"p9_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772.530528px;top:902.560159px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h</font></nobr>");
write("</p>");
write("<p id=\"p9_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698.845027px;top:830.319761px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">g</font></nobr>");
write("</p>");
write("<p id=\"p9_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495.126294px;top:990.693443px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">k</font></nobr>");
write("</p>");
write("<p id=\"p9_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610.711391px;top:1036.927297px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b</font></nobr>");
write("</p>");
write("<p id=\"p9_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:691.620959px;top:989.248635px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">j</font></nobr>");
write("</p>");
write("<p id=\"p9_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.153578px;top:945.904396px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Передняя опора пола B <br>[1.0] 440<br>Передний боковой кронштейн сиденья <br>[1.2] 590<br>Внутреннее нижнее удлинение передней стойки <br>[2.3] 590 или 590, Zn</font> </nobr>");
write("</p>");
write("<p id=\"p9_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149.815813px;top:945.904396px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">h:<br><br>j:<br><br>k:</font></nobr>");
write("</p>");
write("<p id=\"p9_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.982685px;top:383.874106px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Передняя поперечина пола B <br>[1.2] 590<br>Передняя поперечина пола B <br>Удлинитель [1.0] 440<br>Передняя поперечина пола C <br>[1.6] 980<br>Правое среднее сиденье Пластина A <br>[1.2] 440<br>(Транспортные средства, оборудованные сиденьями капитана)<br>Левая средняя пластина сиденья A <br>[1.2] 440<br>Задний центральный кронштейн переднего сиденья <br>[1.4] 440< /br> шрифт></nobr>");
write("</p>");
write("<p id=\"p9_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350.644922px;top:382.429297px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a:<br><br>b:<br><br>c:<br><br>d:<br><br><br>e:<br><br>f:</font></nobr>");
write("</p>");
write("<p id=\"p9_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:850.550469px;top:425.773536px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">e</font></nobr>");
write("</p>");
write("<p id=\"p9_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:879.446744px;top:531.244516px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">f</font></nobr>");
write("</p>");
write("<p id=\"p9_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775.420155px;top:391.098145px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d</font></nobr>");
write("</p>");
write("<p id=\"p9_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703.179469px;top:534.134133px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a</font></nobr>");
write("</p>");
write("<p id=\"p9_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655.500616px;top:395.432569px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c</font></nobr>");
write("</p>");
write("<p id=\"p9_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603.487322px;top:490.789894px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b</font></nobr>");
write("</p>");
write("<p id=\"p9_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:47.234039px;top:678.614927px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Передний элемент жесткости рамы пола B (только правая сторона) <br>[1.4] 590<br>Передний внутренний порог: <br>・Левая сторона [1.2] 780<br>・Левая сторона [1.4] 780<br>Передняя внутренняя часть Ребро жесткости порога< br>[1.4] 980 (только правая сторона)</font></nobr>");
write("</p>");
write("<p id=\"p9_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:27.006647px;top:678.614927px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a:<br><br>b:<br><br><br>c:</font></nobr>");
write("</p>");
write("<p id=\"p9_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304.410882px;top:882.332847px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Правая сторона</font></nobr>");
write("</p>");
write("<p id=\"p9_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38.565157px;top:639.605112px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Комплект рамы переднего пола</font></nobr>");
write("</p>");
write("<p id=\"p9_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366.537872px;top:331.861020px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Передний пол <br>Поперечный элемент Задняя часть Комп.");
write("</p>");
write("<p id=\"p9_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.829107px;top:769.637827px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">b</font></nobr>");
write("</p>");
write("<p id=\"p9_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.748647px;top:745.076092px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">a</font></nobr>");
write("</p>");
write("<p id=\"p9_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154.150255px;top:791.309946px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">c</font></nobr>");
write("</p>");
write("<p id=\"p9_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630.938783px;top:591.926450px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">На иллюстрации показано транспортное средство, оборудованное капитанскими сиденьями.");
write("</p>");
write("<p id=\"p9_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555.808470px;top:685.838966px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">d:<br><br>e:<br><br>f:<br><br>g:</font></nobr>");
write("</p>");
write("<p id=\"p9_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573.146234px;top:685.838966px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Передняя рама пола<br>[1.8] 780<br>Передняя опора пола A <br>[1.0] 590<br>Переборка передней рамы пола <br>[1.0] 590<br>Передний кронштейн среднего сиденья <br> [ 1.2] 270");
write("</p>");
write("</div>");
}